title: National Library Board Singapore
title-abbreviated: NLB
description: The S.U.R.E. campaign is an initiative by the National Library Board to promote the importance of information searching and discernment. The nation-wide campaign was launched in 2013, and Singapore is the first country outside of the United States to promote Information Literacy (IL) on a national scale for the general public.
  Description
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Homepage sections
homepage_hero_i_want_to: true
homepage_resources: false

# Feedback Form URL
feedback_form_url: "https://form.sg/#!/forms/govtech/5a9ce876b3a3b6006e6b8335"

# FAQ URL
faq_url: "/faq/"
faq_url_external: false

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"

exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]

collections:
  about-us:
    output: true
  who-we-are:
    output: true
  resources:
    output: true
  resources-for-teachers-and-students:
    output: true
  resources-for-adults:
    output: true
  resources-for-seniors:
    output: true
  resources-by-format:
    output: true
  ongoing-events:
    output: true
  past-events:
    output: true
  resources-audience:
    output: true
  resources-format:
    output: true
  resources-categories:
    output: true
  school-resources:
    output: true
  elearn:
    output: true
  engage-us:
    output: true
    
# Resources and pagination
resources_name: school-resources
paginate: 12
paginate_path: "/school-resources/page:num"