title: 'National Library Board Singapore'
description: 'The S.U.R.E. campaign is an initiative by the National Library Board to promote the importance of information searching and discernment. The nation-wide campaign was launched in 2013, and Singapore is the first country outside of the United States to promote Information Literacy (IL) on a national scale for the general public.'
url: 'https://sure.nlb.gov.sg'
google_analytics: UA-50449401-2
google_analytics_ga4: G-KZR7EN9JTE
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
resources_name: blog
paginate: 12
paginate_path: '/blog/page:num'
favicon: /images/sure-favicon.jpg
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page

colors:
  primary-color: '#1B98C2'
  secondary-color: '#cc0000'
  media-colors:
    - title: media-color-one
      color: '#007CB3' 
    - title: media-color-two
      color: '#E86826'
    - title: media-color-three
      color: '#ED0000'
    - title: media-color-four
      color: '#007CB3'
    - title: media-color-five
      color: '#E86826'
staging: https://staging.d2vvpgjco2lwa.amplifyapp.com/
prod: https://master.d2vvpgjco2lwa.amplifyapp.com/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
